### ISSUE TITLE
[umbrella for appDir migration] Add missing routes to App Router for `/settings` route group 

### ISSUE THREAD

**Issue by hbjORbj** [calcom/cal.com#16287]
## Nested Routes under `/settings` route group:
- [x] `settings/admin/**/*` #15748 (WIP)
- [x] `settings/billing` #16312 (WIP)
- [x] `settings/developer/**/*` #16286, #16312 (WIP)
- [x] `settings/license-key/**/*` (Benny) #16406
- [x] `settings/my-account/**/*` #16312 (WIP)
- [x] `settings/organizations/attributes/**/*` (Benny) #16406
- [x] `settings/organizations/admin-api` #16312 (WIP)
- [x] `settings/organizations/dsync` (Benny) #16406
- [x] `settings/organizations/privacy` (Benny) #16406
- [x] `settings/organizations/sso` #16312 (WIP)
- [x] `settings/organizations/[id]**/*` #16334 (WIP)
- [x] `settings/organizations/new` #16334 (WIP)
- [x] `settings/platform/**/*` #16334 (WIP)
- [x] `settings/security/**/*` (DONE)
- [x] `settings/teams/**/*` (DONE)

## Routes under `/settings` route group that are in App Router but not in Pages Router
- [x] `settings/teams/[id]/sso` #16288 (WIP)

**Comment by zomars** [comment]
@joeauyeung Can you cross check this list with your Linear issue to avoid stepping on each other toes? 🙏🏽

**Comment by hbjORbj** [comment]
@joeauyeung Sounds great :D Let me know, happy to collaborate :)

**Comment by joeauyeung** [comment]
@hbjORbj feel free to book a time with me [i.cal.com/joe](https://i.cal.com/joe/30min)

**Comment by hbjORbj** [comment]
@joeauyeung Sure thing, I booked a slot ;)

**Comment by hbjORbj** [comment]
@joeauyeung I updated the post based on your PR ;)
