### ISSUE TITLE
[umbrella for appDir migration] Add missing routes to App Router for `/org` route group 

### ISSUE THREAD

**Issue by hbjORbj** [calcom/cal.com#16294]
## Nested Routes under `/org` route group:
- [x] `org/[orgSlug]/[user]/**/*`
- [x] `org/[orgSlug]/team/**/*`
- [x] `org/[orgSlug]/embed.tsx`
- [x] `org/[orgSlug]/index.tsx`
- [x] `org/[orgSlug]/instant-meeting/**/*` #16448
