### ISSUE TITLE
[umbrella for appDir migration] Add missing routes to App Router for `/availability` route group 

### ISSUE THREAD

**Issue by hbjORbj** [calcom/cal.com#16293]
## Nested Routes under `/availability` route group:
- [ ] `availability/[schedule].tsx`
- [ ] `availability/index.tsx`
- [ ] `availability/troubleshoot.tsx`
