### ISSUE TITLE
[umbrella for appDir migration] Add missing routes to App Router for `/auth` route group 

### ISSUE THREAD

**Issue by hbjORbj** [calcom/cal.com#16295]
## Nested Routes under `/auth` route group:
- [x] `auth/verify.tsx` #16444
- [x] `auth/verify-email.tsx`
- [x] `auth/verify-email-change.tsx` #16444
- [x] `auth/signin.tsx`
- [x] `auth/saml-idp.tsx` #16447
- [x] `auth/new.tsx` #16447
- [x] `auth/error.tsx` #16445
- [x] `auth/forgot-password/**/*`
- [x] `auth/oauth2/**/*` #16445
- [x] `auth/platform/**/*` #16445
- [x] `auth/setup/**/*`
- [x] `auth/sso/**/*`
