### ISSUE TITLE
Web3 Contribution Roadmap

### ISSUE THREAD

**Issue by PeerRich** [calcom/cal.com#1682]
## Join our slack: 

1. https://cal.com/slack
2. send a message to `@peer`
3. get invited

___

open tasks, ordered by priority

- [x] replace web3.js with either https://rainbowkit.com/ or https://docs.family.co/connectkit
- [x] move all crypto logic out of the booking page into /packages/apps-store and use an interface instead (same as we do with locations)
- [x] potentially abstract all crypto logic into "Gates" https://github.com/calcom/cal.com/discussions/3297
- [x] support for ERC-721
- [x] #1705
- [ ] advanced filters: min. amount of tokens, length of holding (i.e. only $ORANGE holders with min. 10k tokens and holding them longer than 30 days
- [x] fix linter / typescript errors
- [ ] charge crypto for bookings
- [x] #1822
- [ ] define DAO and auto-donate earned crypto to DAO
- [ ] Support for multiple chains like polygon, celo, gnosis chain, etc
- [ ] (discussion): the ability to stake coins and slash them for no shows

**Comment by elie222** [comment]
Supports ERC721 already, no?

**Comment by PeerRich** [comment]
> Supports ERC721 already, no? Did that change? The logic for both is the same (using `balanceOf`)

can you test? I think last time i tested it didn't work

**Comment by elie222** [comment]
Just tested and works fine

**Comment by ritvij14** [comment]
Hello @PeerRich, we talked on Slack a while back. I am taking up task 4 regarding web3modal. 😄

**Comment by PeerRich** [comment]
> Hello @PeerRich, we talked on Slack a while back. I am taking up task 4 regarding web3modal. 😄 

we maybe will be using wagmi instead

**Comment by ritvij14** [comment]
> we maybe will be using wagmi instead

Ok got it.

**Comment by ritvij14** [comment]
@PeerRich any information regarding the UI of the wallet connection box? Need it to show the multiple wallet options. Also right now wagmi has 3, injected, walletconnect and walletlink.

**Comment by PeerRich** [comment]
> @PeerRich any information regarding the UI of the wallet connection box? Need it to show the multiple wallet options. Also right now wagmi has 3, injected, walletconnect and walletlink.

oh interesting, so web3modal has more connections right? Maybe is it worth to open a PR with web3modal and one with wagmi to see the differences?

we have a Dialog.tsx component which you can use: https://github.com/calcom/cal.com/blob/main/components/Dialog.tsx

**Comment by tmm** [comment]
Injected (i.e. MetaMask), WalletConnect (Rainbow, [and more](https://walletconnect.com/registry/wallets).), and WalletLink (Coinbase Wallet) represent tens of millions of wallets, and are the top three options for [OpenSea](https://opensea.io), [Uniswap](https://uniswap.org), [Foundation](https://foundation.app), etc. The long tail of other wallets aren't used as much, especially because MetaMask and WalletConnect both have support for the two most popular hardware wallets: Ledger and Trezor, which are popular among whales/NFT collectors.

The utility of wagmi seems more useful than a few extra wallet connector. That said, It's pretty easy to [add new connectors](https://wagmi-xyz.vercel.app/guides/connectors) to wagmi if you find yourself needing others.

**Comment by PeerRich** [comment]
> Injected (i.e. MetaMask), WalletConnect (Rainbow, [and more](https://walletconnect.com/registry/wallets).), and WalletLink (Coinbase Wallet) represent tens of millions of wallets, and are the top three options for [OpenSea](https://opensea.io), [Uniswap](https://uniswap.org), [Foundation](https://foundation.app), etc. The long tail of other wallets aren't used as much, especially because MetaMask and WalletConnect both have support for the two most popular hardware wallets: Ledger and Trezor, which are popular among whales/NFT collectors.
> 
> 
> 
> The utility of wagmi seems more useful than a few extra wallet connector. That said, It's pretty easy to [add new connectors](https://wagmi-xyz.vercel.app/guides/connectors) to wagmi if you find yourself needing others.

i am open to compare. would you be down to make a PR with wagmi?

**Comment by PeerRich** [comment]
just tested wagmi and it looks really epic. would you be down to collab on this? we'd may even run a paid project @tmm for "auth with eth" too so people don't need email + password to create an account

**Comment by PeerRich** [comment]
> Hello @PeerRich, we talked on Slack a while back. I am taking up task 4 regarding web3modal. 😄

do you still wanna contribute? do you wanna use wagmi instead + our Dialog.tsx component?

**Comment by ritvij14** [comment]
@PeerRich sure I will give it a try once.

**Comment by PeerRich** [comment]
@agustif i wonder if its worth using https://github.com/Developer-DAO/web3-ui which includes a UI layer 

@tmm how does it compare to wagmi?

**Comment by META-DREAMER** [comment]
Would be nice to see an integration with https://www.npmjs.com/package/@guildxyz/sdk, would be a great turnkey solution to many different complex types of token gating across many chains.

**Comment by PeerRich** [comment]
thank you @hexcowboy for migrating to rainbowkit and extracting the code into the app store + the gates component. checking off some boxes.🎉

**Comment by 0xYootou** [comment]
​Can I pay ERC20 tokens directly for a booking? I am working on this feature based on the cal.com repo code, but not found on the todolist.

**Comment by 0xYootou** [comment]
like this  
<img width="793" alt="image" src="https://user-images.githubusercontent.com/897401/197317298-1906c8a4-3823-4e1d-b4d1-f38a0675944d.png">
