### ISSUE TITLE
[CAL-106] /onboarding - UI issues & small improvements

### ISSUE THREAD

**Issue by Jaibles** [calcom/cal.com#4356]
**General**

- [ ] There's still a long view of the app before onboarding starts.. can we do anything about that? It's not smooth. @zomars https://github.com/calcom/cal.com/issues/4383
- [ ] All Steps: Change "Next Step" in button to "Continue"
- [ ] Something off with a lot of the buttons. Are we using the right components?

---

**Welcome 1/4**

- [ ] The first step is disabled but the style looks weird. Let's just make it editable. https://github.com/calcom/cal.com/issues/4382
![Image](https://user-images.githubusercontent.com/4536123/189480810-483a08d6-8e05-453b-b1b4-4ea1cfdb7572.png)

---

**Connect calendar - No calendar connected 2/4**

- [ ] Button text looks too bold
![Image](https://user-images.githubusercontent.com/4536123/189480889-9fd4aa37-7829-4ca1-93eb-8ca858fc8fcc.png)

---

**Connect calendar - Calendar connected 2/4**

- [ ] We should toggle on at least the first calendar in the list here if not all? https://github.com/calcom/cal.com/issues/4384
- [ ] Change the `mt-7` above the "You can add more...." copy to an `mt-4`. It's way too big right now.
- [ ] THe edit button currently does nothing. Change it to delete so they can remove and add another one. https://github.com/calcom/cal.com/issues/4385

![Image](https://user-images.githubusercontent.com/4536123/189481213-3bb320b3-684b-4920-b35d-6643a71eee89.png)

---

**Availability step 3/4**
Created seperate cards. https://github.com/calcom/cal.com/issues/4380 & https://github.com/calcom/cal.com/issues/4381
- [ ] Would it make more sense to start on a Monday? If we're going to default to Sunday being unavailable it makes more sense imo. 
- [ ] Something wrong with this button visually. Text colour is wrong. Button should say "Copy to all" and Tooltip copy should say "Copy times to all days". If there's issue with spacing to get that button copy right, make the outer padding on all the cards 24px instead of 32px. 
- [ ] Plus button icon colour is off. Are we using the right component here?
- [ ] Can we do shorthand for days here? "Mon" etc. or that complicated with translations?
![Image](https://user-images.githubusercontent.com/4536123/189480290-197ac841-15df-4b0b-9b49-b66ba440bd43.png)

---

**Last step 4/4**

- [ ] Upload button text size & copy is wrong - https://github.com/calcom/cal.com/issues/4343
- [ ] Remove that Title

![Image](https://user-images.githubusercontent.com/4536123/189481324-2671767f-3d16-468a-bbc4-293b549c9daa.png)

**Comment by PeerRich** [comment]
good ticket but definitely not a quick win. i feel like this should be multiple tickets / PRs too

**Comment by emrysal** [comment]
I'm handling the step3 issues due to shared component with availability single view.

**Comment by zomars** [comment]
Left some comments about the onboarding flash in #4383

**Comment by matheusmuniz03** [comment]
Hey @Jaibles, how are you? I would like your attention on this issue.

Currently steps 1 (welcome) and 2 (connect calendar - No calendar connected) are fully resolved.

Step 3 (availability) is practically resolved, just missing the last check, but I just opened an [issue](https://github.com/calcom/cal.com/issues/4993) that covers this issue.

Here are the prints in question:
![Captura de tela de 2022-10-13 16-18-50](https://user-images.githubusercontent.com/87545749/195690144-78dd4d26-bd60-4247-af78-6e4a460b8b13.png)
![Captura de tela de 2022-10-13 16-19-25](https://user-images.githubusercontent.com/87545749/195690160-e61585f4-29c0-47dc-85ed-4ac798bafe7c.png)
![Captura de tela de 2022-10-13 16-19-41](https://user-images.githubusercontent.com/87545749/195690169-6755e450-5904-4181-b202-6dbf7635584d.png)

**Comment by matheusmuniz03** [comment]
Now steps 2 (Connect Calendar - Calendar connected) are linked in the issue (I commented my solution in the issue) and 4 (Last step) just need to remove the Title. Do you want to close this entire issue and just open another one talking about removing the title or do you think this is good?
@Jaibles
