### ISSUE TITLE
[CAL-1777] Major module refactor

### ISSUE THREAD

**Issue by zomars** [calcom/cal.com#9126]
Needed for calcom/cal.com#4847

* [X] /attendees calcom/api#176
* [X] /availabilities calcom/api#177
* [ ] /availability
* [X] /booking-references calcom/api#180
* [X] /bookings
* [X] /custom-inputs calcom/api#184
* [ ] /destination-calendars
* [X] /event-types calcom/api#181
* [X] /hooks calcom/api#186
* [X] /me
* [x] /memberships calcom/api#204
* [ ] /payments
* [X] /schedules calcom/api#185
* [x] /selected-calendars calcom/api#193
* [X] /teams
* [X] /users

> From [Linear-GitHub Sync](https://synclinear.com)

<sub>[CAL-1777](https://linear.app/calcom/issue/CAL-1777/[cal-135]-major-module-refactor)</sub>
