### ISSUE TITLE
[CAL-2125] CalDAV Feature & Performance Improvement Checklist

### ISSUE THREAD

**Issue by alishaz-polymath** [calcom/cal.com#9990]
## CalDAV feature-list thread 🎊

This issue/feature request serves as the checklist for the next steps to take CalDAV out of Beta and make it stable. This thread also includes a few features that are desirable to make CalDAV UX better overall with the primary aim of making it more transparent, reliable and reducing confusion around this integration.

### Beta specific

* [ ] Improve "Cannot add this CalDAV account" error to provide more context, whether it is authentication failed, bad CalDAV homeURL or log and provide error code
* [ ] Handle a timeout in CalDAV which has often resulted in infinite loading of /calendars page
* [ ] Add "Digest" auth as an option. Currently we use Basic Auth which is the most common one, but some CalDAV providers prefer Digest so it would be neat to have support for Digest

### UX, performance and reliability improvement

* [ ] In the CalDAV setup page, it would be a good idea to have performance indicator which confirms that the performance is good with the CalDAV added. If the performance is below par, require confirmation from the user to add the connection (and explicitly mention risks associated with a poor performing calendar connection)
* [ ] Allow basic event CRUD testing for the CalDAV calendar being added which allows users to confirm at the time of setup if any of the requests are failing (Create, Read, Update or Delete) for the test event
* [ ] During the event CRUD testing above, if they face any errors, they should be provided the ICAL data received (empty, if empty) so that they can then contact support with relevant information allowing us to debug better and quickly
* [ ] Provide an ICAL parser interface for the users to simply copy-paste ICS in the textfield and show them the information inferred by the ICAL parser at [Cal.com](http://Cal.com). This would make it more transparent as to what their ICS represents for us, and if there's soemthing we need to improve on our end. This should help in debugging a lot of potential issues concerned with ICAL data parsing.
* [ ] ICS feed support for checking against double bookings [REF](https://github.com/calcom/cal.com/issues/3167)

If you guys find you have more stuff/ideas/requests which isn't already mentioned, please feel free to comment. 🙏
🚀 🚀 🚀 🚀 🚀

<sub>From [SyncLinear.com](https://synclinear.com) | [CAL-2125](https://linear.app/calcom/issue/CAL-2125/caldav-feature-and-performance-improvement-checklist)</sub>

**Comment by alishaz-polymath** [comment]
Not prioritized at the moment! Can revisit.
